### ISSUE TITLE
Developing addon requires container restart on every code change

### ISSUE THREAD

**Issue by 0x2206** [WebThingsIO/gateway-docker#44]
I am using Docker image of the gateway to develop an addon on MacOS. I was able to run container with mounted volume but it looks every change in addon source code requires me to kill and re-run container again. Surely I am doing something wrong here? Please advise.

This is how I run the container:

```sh
docker run \
    -p 8080:8080 \
    -p 4443:4443 \
    -e TZ=America/Los_Angeles \
    -v /path/to/data/on/host:/home/node/.mozilla-iot \
    --log-opt max-size=1m \
    --log-opt max-file=10 \
    --name webthings-gateway \
    mozillaiot/gateway:latest
```

Addon code is placed at `/path/to/data/on/host/addons/my-addon`.

Please note I removed running it in detached mode to see logs in terminal. The rest is taken directly from `README.md`.

**Comment by 0x2206** [comment]
Just to add one thing. Addon code changes are visible inside running container.

**Comment by 0x2206** [comment]
It looks my issue is not related to container but to how gateway works. Disabling an re-enabling addon at http://localhost:8080/settings/addons makes gateway to load updated code of addon, just as I would expect.

Anyway I am happy to hear if there is more correct way.

**Comment by mrstegeman** [comment]
Disabling and re-enabling the add-on, or restarting the gateway, is the correct thing to do.
